name: Check ROS Build
on:
  pull_request:
    branches:
      - master
    paths:
      - ROS/src/**
      - serial-comms/cpp/beluga-serial/**

jobs:
  build_beluga_package:
    runs-on: ubuntu-22.04
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: beluga
          target-ros2-distro: humble
          skip-tests: true
