name: Check ROS Build
on:
  pull_request:
    branches:
      - master
    paths:
      - ROS/src/**
      - serial-comms/cpp/beluga-serial/**

jobs:
  build_beluga_package:
    runs-on: ubuntu-22.04
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-latest
    steps:
      - name: Build ROS package
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: beluga
          target-ros2-distro: humble
          skip-tests: true
